# Generated by Django 6.0.3 on 2026-03-26 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_importproduct_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.branch'),
        ),
    ]
