# Generated by Django 6.0.3 on 2026-04-09 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_client_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
        ),
    ]
