# Generated by Django 6.0.3 on 2026-07-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_paydebt_client_alter_sale_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('dona', 'Dona'), ('kg', 'Kg'), ('gramm', 'Gramm'), ('litr', 'Litr'), ('quti', 'Quti'), ('paket', 'Paket')], max_length=20, null=True),
        ),
    ]
